---
apiVersion: apps/	v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins-apps
    environment: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins-apps
      environment: prod
  strategy:
    type = RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
         app: jenkins-apps
         environment: prod
  spec:
    containers:
      - name: jenkins-container
        image: jenkins:1.651.1
        ports:
          - containerPort: 8080
            protocol: TCP
            
            
         
        
      
      
      

      
