---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment-demo
  labels:
    name: jenkins-app
    envornment: prod
spec:
  minReadySeconds: 15
  replicas: 2
  selector:
    matchLabels:
      app: jenkins-app
      envornment: prod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: jenkins-app
        envornment: prod
        version: 1.16
    spec:
      containers:
        - name: jenkins-container
          image: jenkins:latest
          ports:
            - containerPort: 8080
              protocol: TCP
   
  
