---
apiVersion: v1
kind: ReplicaSet
metadata:
  name: http_replica
  labels:
    app: httpd
spec:
  minReadySeconds: 5
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd_container
          image: httpd:latest
          ports:
            - containerPort: 80
              protocol: TCP